# Site settings
title: Alastair McFarlane
email: alastair@alastairmcfarlane.co.uk
description: "Developer. Architect. Problem Solver."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/alitheg
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/users/1254863/alitheg
  - title: bitbucket 
    url: https://bitbucket.org/alitheg/
  - title: github
    url: http://github.com/alitheg

# Postal address (add as many lines as necessary)
address:
  - line: 
  - line: 

# Build settings
markdown: kramdown
permalink: pretty
